/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.4 */
/* Wed Jan  8 10:36:46 2020 */

/* parameterized module instance */
sine_rom __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), .Q( ));
