/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 5.4 */
/* Mon Nov 22 22:01:49 2021 */

/* parameterized module instance */
rom_sine __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), .Q( ));
